Model_Params:
  learning_rate: [0.01, 0.05, 0.1,0.15]
  max_depth: [1, 2, 3, 4, 5, 6, 7, 8, 9,10]
  max_features: ['log2', 'sqrt']
  min_samples_leaf: [1, 2, 4]
  min_samples_split: [2, 5, 10]
  n_estimators: [200, 400, 600, 800,1000, 1200, 1400, 1600,1800, 2000]

Final_Params:
  n_estimators: 200 
  min_samples_split: 5 
  min_samples_leaf: 4 
  max_features: sqrt 
  max_depth: 2 
  learning_rate: 0.01